name: CTE
authors:
  - Flauschi
  - Cake-chan
version: 69.420
main: com.osterph.cte.CTE
depend: [PlayHillsAPI]
commands:
  start:
  countdown:
  setteam:
  dev:
  suddendeath:
  emotes:
    aliases:
      - emote
      - e
      - listemote
      - listemotes
      - emotelist
