name: Capture the egg
authors:
  - Flauschi
  - Cake-chan
version: 69.420
main: com.osterph.cte.CTE
commands:
  start:
  countdown:
  setteam:
  dev:
  egg:
  animation:
  emotes:
    aliases:
      - emote
      - e
      - listemote
      - listemotes
      - emotelist
